# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    - tagliatelle
    - nonamedreturns
    - paralleltest
    - tparallel
    - noinlineerr
    - ireturn
    - gochecknoglobals
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocritic
    - exhaustive
    - gocognit
    - depguard
    - errcheck
    - cyclop
    - gosec
    - err113
    - perfsprint
    - wsl
    - errorlint
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    varnamelen:
      ignore-names:
        - err
        - tc
        - tt
      ignore-decls:
        - c echo.Context
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
        - T any
        - m map[string]int
        - w http.ResponseWriter
        - r *http.Request
        - fn func(r *Router)
    tagalign:
      align: false
      sort: false
      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
      strict: true
