# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  lint :
    desc: Run golangci-lint
    cmds:
      - golangci-lint run
